### ISSUE TITLE
Feature request: Scala 2.12 support

### ISSUE THREAD

**Issue by holograph** [scoverage/sbt-scoverage#126]
The title says it all, I think :-)

**Comment by sksamuel** [comment]
Will definitely come once 2.12 is a bit more stable I think. The reason why is that the AST that the compiler generates might not be locked down yet and that's what the scoverage plugin has to manipulate.

**Comment by milessabin** [comment]
Can I bump this ... it's a blocker for shapeless adding support for Scoverage because our build matrix includes 2.12.0-M3 and there doesn't appear to be any straightforward way to load it for a subset of Scala versions.

**Comment by sksamuel** [comment]
https://github.com/scoverage/scalac-scoverage-plugin/issues/152
Better track it on the plugin itself, as it's not an sbt feature strictly speaking. I have a 2.12 build locally that is currently failing on 6 tests, so its on my radar this week or so to get those finished.

**Comment by milessabin** [comment]
Gotcha ... thanks.

**Comment by khronnuz** [comment]
@sksamuel We are trying to add scoverage to milessabin/shapeless and are currently blocked because current version of plugin always tries to load scala version specific runtime plugins. I see that this is fixed in master but there is no version released. Any plans to release it soon?

Btw, sorry about double posting, but it's been a few days already https://groups.google.com/forum/#!topic/scala-code-coverage-tool/OUiAS1EVmcQ

**Comment by sksamuel** [comment]
If its just a release you need I can do it later today.

**Comment by gslowikowski** [comment]
I would like to test it before release. It's not even merged to master and you commented a week ago that there are still failing tests. Has something changed since then?

**Comment by sksamuel** [comment]
I think he's talking about the other issue, not 2.12 support, just happens
to be in this thread.

**Comment by gslowikowski** [comment]
If it' about #153, your commit broke `sbt-scoverage`. I wrote about it.

**Comment by khronnuz** [comment]
Oh yes. Sorry about not being clear. Yes, what I mean is that we cross compile to 2.12 and without #126 or #153 we cannot use scoverage plugin

**Comment by magicknot** [comment]
Any news on this?

**Comment by gslowikowski** [comment]
See https://github.com/scoverage/scalac-scoverage-plugin/pull/177#issuecomment-247872203.

**Comment by MichaelJAllen** [comment]
As Scala 2.12.0 was officially released today, do you have a schedule for releasing a compatible version of scoverage?

(Thanks for providing such a great tool, BTW!)

**Comment by gslowikowski** [comment]
Version `1.5.0` with Scala 2.12 support released.

**Comment by tobyweston** [comment]
👍 thanks
